import articles from "../data/articles-index.generated.json";
import type { ArticleMeta } from "./article-schema";

/**
 * Pre-built content snapshot (metadata only — no rendered bodies).
 * Generated by `scripts/build-content.ts` (auto-run via `predev` /
 * `prebuild` package.json hooks). Identical data on server and client.
 * Bodies live in article-bodies.generated.json, served exclusively via
 * the server fn in `article-body.ts` so they never enter the client
 * bundle or list-page SSR payloads.
 */
const ALL_ARTICLES = articles as ArticleMeta[];

export function getAllArticles(): ArticleMeta[] {
	return ALL_ARTICLES;
}

export function getArticleMeta(slug: string): ArticleMeta | undefined {
	return ALL_ARTICLES.find((a) => a.slug === slug);
}

const PLACEHOLDER_THUMBNAIL = "/images/placeholder/sunflower.webp";

/**
 * Resolve a stored thumbnail path to the optimized WebP sibling that
 * `scripts/optimize-images.ts` generates at build time. Empty input
 * returns the placeholder. WebP is universal in 2026 — no `<picture>`
 * fallback needed. Originals stay on disk if a render ever needs them.
 */
export function thumbnailUrl(src: string | null | undefined): string {
	if (!src) return PLACEHOLDER_THUMBNAIL;
	return src.replace(/\.(jpe?g|png)$/i, ".webp");
}

/**
 * Responsive srcset string for a thumbnail. Pairs with
 * `optimize-images.ts` which emits `<name>-480w.webp`,
 * `<name>-768w.webp` and `<name>.webp` (1080w canonical) per source.
 *
 * Browsers pick the smallest variant that satisfies the `sizes` hint —
 * mobile fetches 480w even when the canonical `src` is the 1080w file.
 */
export function thumbnailSrcSet(src: string | null | undefined): string {
	const base = thumbnailUrl(src);
	if (base === PLACEHOLDER_THUMBNAIL) return base;
	const stem = base.replace(/\.webp$/i, "");
	return `${stem}-320w.webp 320w, ${stem}-480w.webp 480w, ${stem}-672w.webp 672w, ${stem}-768w.webp 768w, ${base} 1080w`;
}
