import articles from "../data/articles.generated.json";
import type { Article } from "./article-schema";

/**
 * Pre-built content snapshot. Generated by `scripts/build-content.ts`
 * (auto-run via `predev` / `prebuild` package.json hooks). Identical
 * data on server and client — no markdown pipeline shipped to browser.
 */
const ALL_ARTICLES = articles as Article[];

export function getAllArticles(): Article[] {
	return ALL_ARTICLES;
}

export function getArticleBySlug(slug: string): Article | undefined {
	return ALL_ARTICLES.find((a) => a.slug === slug);
}

export function getArticleSlugs(): string[] {
	return ALL_ARTICLES.map((a) => a.slug);
}

const PLACEHOLDER_THUMBNAIL = "/images/placeholder/sunflower.webp";

/**
 * Resolve a stored thumbnail path to the optimized WebP sibling that
 * `scripts/optimize-images.ts` generates at build time. Empty input
 * returns the placeholder. WebP is universal in 2026 — no `<picture>`
 * fallback needed. Originals stay on disk if a render ever needs them.
 */
export function thumbnailUrl(src: string | null | undefined): string {
	if (!src) return PLACEHOLDER_THUMBNAIL;
	return src.replace(/\.(jpe?g|png)$/i, ".webp");
}
