import { writeFileSync } from 'node:fs'
import { defineConfig, type Plugin } from 'vite'
import { devtools } from '@tanstack/devtools-vite'

import { tanstackStart } from '@tanstack/react-start/plugin/vite'

import viteReact from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { cloudflare } from '@cloudflare/vite-plugin'

/**
 * Captures the built stylesheet during the client build and writes it to a
 * generated module. The server build (which runs after the client build)
 * imports it and inlines the CSS into <head> — removing the render-blocking
 * CSS request, the last ~0.5s on Lighthouse's throttled-mobile critical path.
 * (`styles.css?inline` can't do this: vite:asset crashes resolving the font
 * url() placeholders inside a JS string, and it would bloat the client
 * entry with a second copy of the sheet.)
 */
function emitInlineCss(): Plugin {
  return {
    name: 'emit-inline-css',
    apply: 'build',
    applyToEnvironment: (env) => env.name === 'client',
    generateBundle(_options, bundle) {
      const css = Object.values(bundle).find(
        (f) => f.type === 'asset' && f.fileName.endsWith('.css'),
      )
      if (css?.type !== 'asset') return
      writeFileSync(
        'src/data/inline-css.generated.ts',
        `/* Auto-generated by emit-inline-css (vite.config.ts). Do not edit. */\nexport const css: string = ${JSON.stringify(String(css.source))}\n`,
      )
    },
  }
}

const config = defineConfig({
  resolve: { tsconfigPaths: true },
  build: {
    /* No source maps in the production build. Emitting them publishes the
       full original source (incl. bundled library internals) as world-
       readable .js.map artifacts next to the bundle — an info-disclosure
       surface and the source of react-doctor artifact-secret-leak /
       artifact-baas-authority-surface findings. Lighthouse's
       valid-source-maps is an informational (unweighted) audit, so this
       does not affect the Best-Practices score. */
    sourcemap: false,
  },
  plugins: [
    devtools(),
    cloudflare({ viteEnvironment: { name: 'ssr' } }),
    tailwindcss(),
    tanstackStart(),
    viteReact(),
    emitInlineCss(),
  ],
})

export default config
